name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 21.2.0
        - name: Install
          run: npm install
        - name: Test
        # note any environment vars has to be added below the env:otherwise it will not run this ci.yml file on whatever we configure this run on.
          env: 
            BROWSERSTACK_USERNAME: ${{ secrets.BS_USER}}
            BROWSERSTACK_ACCESS_KEY: ${{ secrets.BS_KEY}}
          run: npx wdio config/browserstack-config/wdio.android.bs.conf.js --spec test/specs/note.app.webview.android.js
          
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
